# coding: utf-8
from diskvert import col2python
dd,pd = col2python('MDFK.dat')
dw,pw = col2python('MWFK.dat')
plt.plot(pw['h'],pw['temp'])
plt.plot(dw['h'], dw['temp'], label = 'compt')
plt.yscale('log')
plt.plot(dd['h'], dd['temp'], label = 'dyfu')
dc,pc = col2python('MCFK.dat')
plt.plot(dc['h'], dc['temp'], label = 'corona')
plt.plot(dd['h'], dd['tcompt'], label = 'dyfu tcompt')
plt.ylim(1e5,1e8)
plt.ylim(3e5,1e9)
plt.plot(dd['h'], np.sqrt(dd['trad']**2 + dd['tcompt']**2), label = 'dyfu szac')
plt.plot(dd['h'], (dd['trad']**3 + dd['tcompt']**3)**0.33, label = 'dyfu szac')
plt.plot(dd['h'], dd['trad'] + dd['tcompt'], label = 'dyfu szac')
plt.plot(dd['h'], (dd['trad']**4 + dd['tcompt']**4)**0.25, label = 'dyfu szac')
fig, ax = plt.subplots()
ax.plot(dd['h'], dd['rho'], label = 'dyfu')
ax.set_yscale('log')
ax.plot(dw['h'], dw['rho'], label = 'compt')
ax.plot(dc['h'], dc['rho'], label = 'corona')
