#!/usr/bin/env python
# coding: utf-8

from pickle import dump as pidump
from gzip import open as gzopen
from re import compile as re_compile
from sys import argv
from diskvert.col2python import col2python

if len(argv) == 1:
    print(u"usage: col2python [FILE1] [FILE2] ...")
    print(u"files must be of type: .tar.gz, .tgz or .dat")
    exit(0)

rexp_allowed = re_compile(r'(\.tar\.gz|\.tgz|\.dat)$')
for fn in argv[1:]:
    try:
        p = col2python(fn)
        if p != None:
            pidump(p, gzopen(sub(rexp_allowed,'.pickle.gz',fn),'wb'))
    except Exception as e:
        print u"col2python error: %s" % e
